<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF=" UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Billout</title>
    <link rel="stylesheet" href="billout-style.css">
</head>

<body>
    <div class="billout-container">
        <div class="billout-header">
            <h1 class="restaurant-name">Your Restaurant Name</h1>
            <p class="address">123 Food Street, Delicious City, PH</p>
            <p class="contact">Phone: (0912) 345-6789</p>
        </div>

        <h2 class="document-title">ORDER BILLOUT</h2>

        <div class="order-details">
            <div class="detail-row">
                <span class="label">Order No:</span>
                <span class="value" id="billout-order-no">ORD-XYZ78901</span>
            </div>
            <div class="detail-row">
                <span class="label">Date:</span>
                <span class="value" id="billout-date">July 9, 2025</span>
            </div>
            <div class="detail-row">
                <span class="label">Time:</span>
                <span class="value" id="billout-time">20:30:45 PST</span>
            </div>
            <div class="detail-row">
                <span class="label">Customer Name:</span>
                <span class="value" id="billout-customer-name">Juan Dela Cruz</span>
            </div>
            <div class="detail-row">
                <span class="label">Contact No:</span>
                <span class="value" id="billout-customer-contact">09XX-XXX-XXXX</span>
            </div>
            <div class="detail-row">
                <span class="label">Delivery Address:</span>
                <span class="value" id="billout-delivery-address">Apt 101, Bldg B, Highrise Residences, Bagac</span>
            </div>
            <div class="detail-row">
                <span class="label">Status:</span>
                <span class="value status-value status-done" id="billout-status">Done (Ready for Dispatch)</span>
            </div>
        </div>

        <table class="billout-item-table">
            <thead>
                <tr>
                    <th>QTY</th>
                    <th>ITEM</th>
                    <th>REMARKS</th>
                    <th>UNIT PRICE</th>
                    <th>AMOUNT</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>2</td>
                    <td>Chicken Adobo (Large)</td>
                    <td>Extra gravy, less salt</td>
                    <td>₱ 250.00</td>
                    <td>₱ 500.00</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Garlic Rice (Extra)</td>
                    <td>Well done</td>
                    <td>₱ 60.00</td>
                    <td>₱ 60.00</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Bottled Water</td>
                    <td></td>
                    <td>₱ 25.00</td>
                    <td>₱ 75.00</td>
                </tr>
            </tbody>
        </table>

        <div class="billout-summary">
            <div class="summary-row">
                <span class="label">Subtotal:</span>
                <span class="value" id="billout-subtotal">₱ 635.00</span>
            </div>
            <div class="summary-row">
                <span class="label">Delivery Fee:</span>
                <span class="value" id="billout-delivery-fee">₱ 50.00</span>
            </div>
            <div class="summary-row">
                <span class="label">Discount:</span>
                <span class="value" id="billout-discount">₱ 0.00</span>
            </div>
            <div class="summary-row total-row">
                <span class="label">TOTAL AMOUNT DUE:</span>
                <span class="value" id="billout-total-amount-due">₱ 685.00</span>
            </div>
        </div>

        <div class="notes-section">
            <p><strong>Internal Notes/Special Instructions for Delivery:</strong></p>
            <p id="internal-notes">Call customer upon arrival. Building has strict security.</p>
        </div>

        <div class="billout-footer">
            <p>Bill Generated by: Dispatcher 02</p>
            <p class="timestamp">Printed: July 9, 2025 20:40:00 PST</p>
        </div>
    </div>
</body>

</html>